### ISSUE TITLE
The color contrast of the text is too weak to read

### ISSUE THREAD

**Issue by gfx** [Rust-GCC/Rust-GCC.github.io#22]
Hello!

I've found the text of the blog posts is too light and thus hard to read for weak-sighted people like me:

https://rust-gcc.github.io/2023/04/24/gccrs-and-gcc13-release.html

<img width="915" alt="Screenshot 2023-04-25 at 12 59 52" src="https://user-images.githubusercontent.com/101800/234171975-d0489a1c-91e6-4563-9ebf-cefe8d586a0e.png">

I've made a pull-request for everyone using the `jekyll-theme-minimal` (https://github.com/pages-themes/minimal/pull/284), but it would be nicer if the author of this repository changed the color theme of the repository.

**Comment by CohenArthur** [comment]
thank you @gfx for the issue :) we'll change the theme soon and we'll go for a more contrasted color palette

**Comment by CohenArthur** [comment]
Fixed by #39 I believe? @gfx I'd love it if you could have a look and let us know :) sorry it took so long, we were very busy with other stuff but thankfully @GuillaumeGomez came along to help us

**Comment by gfx** [comment]
Perfect! I have no trouble with reading. Thank you.
